### ISSUE TITLE
order/ endpoint forces use of String for RecordId when POSTing an order, previously was Integer

### ISSUE THREAD

**Issue by willmacs** [eodms-sgdot/py-eodms-rapi#6] opened 2022-04-07 21:32 UTC
###### IMPACT

Get HTTP-400 errors if don’t use stringified integer RecordIds

**Comment by keballantyne** [comment] 2022-04-08 18:07
Issue caused by adding "?format=json" to the order POST. Issue is fixed in v1.3.1.

**Closed by keballantyne** 2022-04-08 18:07 UTC
